// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_tutorial

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User string `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}
